[window]

decorations = "None"

resize_increments = true

opacity = 0.95

padding = { x = 8, y = 8 }

[font]

size = 12

[font.normal]

family = "JetBrainsMono Nerd Font"

[cursor]

style = "Beam"

[colors.primary]

background = "#1e1e2e"

foreground = "#cdd6f4"
