[main]
font=JetBrainsMono Nerd Font:style=Bold:size=12.5
dpi-aware=yes
fields=name,generic,comment,exec
terminal=alacritty
prompt="❯ "
layer=top
width=32
horizontal-pad=20
vertical-pad=14
inner-pad=10

[colors]
background=1E1E2ECC
text=CDD6F4FF
# Строгий темный серо-синий цвет для совпадений
match=6C7086FF
selection=B4BEFEFF
selection-text=11111BFF
selection-match=6C7086FF
border=B4BEFEFF

[border]
width=2
radius=8
