# НАСТРОЙКА ФОНА
background {
    monitor =
    path = /usr/share/backgrounds/train_tracks_in_a_forest.jpg
    color = rgba(25, 20, 20, 1.0)

    # Эффект размытия заднего плана (очень красиво выглядит)
    blur_passes = 2
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# ЧАСЫ
label {
    monitor =
    text = $TIME
    color = rgb(205, 214, 244) # Текст цвета Catppuccin Text
    font_size = 90
    font_family = JetBrains Mono Nerd Font Bold
    position = 0, 200
    halign = center
    valign = center
}

# ФОРМА ВВОДА ПАРОЛЯ
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2 # Размер точек пароля
    dots_spacing = 0.2 
    dots_center = true
    
    # Цвета элементов в стиле Catppuccin
    outer_color = rgb(137, 180, 250) # Голубая рамка (Blue)
    inner_color = rgb(30, 30, 46)     # Темное поле ввода (Base)
    font_color = rgb(205, 214, 244)  # Цвет символов
    
    fade_on_empty = false
    placeholder_text = <i>Введите пароль...</i>
    hide_input = false
    
    position = 0, -20
    halign = center
    valign = center
}
